const userCode = {
    USER_LOGIN_SUCCESS: '001',
    FAIL_USER_NAME_OR_PASSWORD_ERROR: '002',
    NOT_EXIST_USER_NAME: '003',
    USER_SINGUP_SUCCESS: '004',
    ERROR_USER_NAME: '005',
    ERROR_EMAIL: '006',
    ERROR_PASSWORD: '007',
    ERROR_PASSWORD_CONFIRM: '008',
    FAIL_USER_NAME_IS_EXIST: '009',
    FAIL_EAMIL_IS_EXIST: '010',
    SYS_ERROR: '011'
}


module.exports = userCode;